# Generated by Django 4.0.5 on 2022-08-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_rename_bid_film'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Film',
            new_name='Bid',
        ),
    ]
